name: Build Linux Artifacts

on:
  workflow_dispatch:
    inputs:
      tags:
        description: "Version tags"
        required: true
        type: string

jobs:
  build:
    runs-on: "ubuntu-latest"
    container:
      image: sjzsdu/yao-build:0.10.4

    steps:
      - name: Build
        run: |
          export PATH=$PATH:/github/home/go/bin
          /app/build.sh
          ls -l /data

      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: yao-linux
          path: |
            /data/*

      - name: Create Release
        uses: softprops/action-gh-release@v1
        if: success()
        continue-on-error: true
        with:
          tag_name: ${{ github.event.inputs.tags }}
          name: Release ${{ github.event.inputs.tags }}
          files: /data/*
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
